name: release

on:
  push:
    tags:
      - 'v*'

jobs:

  upload-assets:
    name:    upload assets
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: install bazel
        run: |
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -

          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" \
            | sudo tee /etc/apt/sources.list.d/bazel.list

          sudo apt update && sudo apt install bazel
        env:
          APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: DontWarn

      - name: run tests
        run: |
          bazel test --platforms="@io_bazel_rules_go//go/toolchain:linux_amd64" //...

      - name: build linux binary
        run: |
          bazel build --platforms="@io_bazel_rules_go//go/toolchain:linux_amd64" //...


      - name: build macos binary
        run: |
          bazel build --platforms="@io_bazel_rules_go//go/toolchain:darwin_amd64" //...

      - name: create_release
        id:   create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:     ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft:        true
          prerelease:   false


      - name: upload linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bazel-bin/cmd/google-kms-x509/linux_amd64_pure_stripped/google-kms-x509
          asset_name: google-kms-x509-linux-amd64-${{ github.ref }}
          asset_content_type: application/octet-stream

      - name: upload macos binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bazel-bin/cmd/google-kms-x509/darwin_amd64_pure_stripped/google-kms-x509
          asset_name: google-kms-x509-macos-amd64-${{ github.ref }}
          asset_content_type: application/octet-stream
